var question1 = ["student names for future:"];
document.write(question1 + "<br>");
var question2 = ["ali ", "ayesha ", "furqan ", "aliyan "];
document.write(question2[1] + "<br>");
document.write(question2[2] + "<br>");
document.write(question2[0] + "<br>");
document.write(question2[3] + "<br>");
var question3 = ["this line is stringed array"];
document.write(question3 + "<br>");
var question4 = ["4"];
document.write(question4 + 5 + "<br>");
var question5 = ["Azlan ","ali "];
document.write(question5[0] + "<br>");
var question6 = ["Azlan ","Ali ","7","8",];
document.write(question6[0] + question6[2] + " " + question6[1] +  question6[3] + "<br>");
var question7 = ["QUALIFICATIONS :","SSC", "HSC", "BCS" , "BS" , "BCOM ", "MS", "MPhil", "PhD"];
document.write(question7[0] + "<br>");
document.write(question7[5] + "<br>");
document.write(question7[1] + "<br>");
document.write(question7[2] + "<br>");
document.write(question7[3] + "<br>");
document.write(question7[8] + "<br>");
document.write(question7[7] + "<br>");
document.write(question7[4] + "<br>");
var question8 = ["SCORES :","", "", "" ];
document.write(question8[0] +"<br>");
document.write(question8[1] + "Score of Ali is 320/500. percentage = 64% " + "<br>");
document.write(question8[2] + "Score of Aliyan is 398/500. percentage = 74% " +  "<br>");
document.write(question8[3] + "Score of Azlan is 478/500. percentage = 95% " + "<br>");
var question10 = ["Student Scores:"];
document.write(question10 +"<br>");
document.write("Scores Of Students = 329,480.230.120" + "<br>");
document.write("Ordered Scores Of Students = 120,230.329.480" +  "<br>");
var question11 = ["Cities List:"];
document.write(question11 +"<br>");
document.write("Karachi, Lahore, Quetta, Peshawar" + "<br>");
var question11 = ["Selected Cities List:"];
document.write(question11 +"<br>");
document.write("Karachi, Lahore" +  "<br>");
var question12 = ["This", " is ", " my ", " cat." +  "<br>"];
document.write(question12[0] + question12[1] + question12[2] + question12[3])
var question13 = ["DEVICES:"];
document.write(question13 +"<br>");
document.write("Printer, Moniter, Keyboard, Mouse" + "<br>");
var question13 = ["Out:"];
document.write(question13 +"<br>");
document.write("Keyboard" + "<br>");
var question13 = ["Out:"];
document.write(question13 +"<br>");
document.write("Mouse" + "<br>");
var question13 = ["Out:"];
document.write(question13 +"<br>");
document.write("Printer" + "<br>");
document.write(question13 +"<br>");
document.write("Moniter" + "<br>");
var question14 = ["DEVICES:"];
document.write(question14 +"<br>");
document.write("Printer, Moniter, Keyboard, Mouse" + "<br>");
var question14 = ["Out:"];
document.write(question14 +"<br>");
document.write("Moniter" + "<br>");
var question14 = ["Out:"];
document.write(question14 +"<br>");
document.write("Printer" + "<br>");
var question14 = ["Out:"];
document.write(question14 +"<br>");
document.write("Mouse" + "<br>");
document.write(question14 +"<br>");
document.write("Keyboard" + "<br>");
var question15 = ["MANUFACTURES :","Apple", "Sony", "Haier" , "Samsung" , "Motorlla ", "Nokia"];
document.write(question15[0] + "<br>");
document.write(question15[5] + "<br>");
document.write(question15[1] + "<br>");
document.write(question15[2] + "<br>");
document.write(question15[3] + "<br>");
document.write(question15[4] + "<br>");
document.write(question15[6] + "<br>");